
export const threeMCareData: { [model: string]: { name: string; charge: number }[] } = {
  "Ciaz": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Ertiga": [ 
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Fronx": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Baleno": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Grand Vitara": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "S-Cross": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Brezza": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "XL6": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Dzire": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Eeco": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Eeco Cargo": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Swift": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Jimny": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Alto K10": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Alto 800": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Celerio": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Ignis": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Wagon R": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "S-Presso": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Ritz": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ]
};
