
export const threeMCareData: { [model: string]: { name: string; charge: number }[] } = {
  "CIAZ DIESEL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "CIAZ PETROL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Ciaz": [ // Alias for CIAZ PETROL and DIESEL
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ERTIGA DIESEL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ERTIGA PETROL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
   "Ertiga": [ // Alias
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Fronx": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Baleno": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Grand Vitara": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "S-Cross": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Brezza": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "XL6": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
   "DAZZLING NEW DZIRE": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "DZIRE TOUR DIESEL": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "EECO": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "EECO K12N 2022": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "EPIC NEW SWIFT": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Jimny 5 Door Domestic P74": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "MARUTI EECO PETROL": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "New Dzire Diesel": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "New Dzire Petrol": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "NEW SWIFT DZIRE TOUR S PETROL": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "NEW SWIFT PETROL": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Swift": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Dzire": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "SWIFT DZIRE": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "SWIFT NEW / DZIRE NEW PETROL": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "SWIFT NEW/  DZIRE NEW DIESEL": [
    { name: "INTERIOR CLEANING", charge: 1250 },
    { name: "BODY RUBBING & POLISHING", charge: 1250 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2300 },
    { name: "PAINT PROTECTION", charge: 3300 },
    { name: "SILENCER COATING", charge: 800 },
    { name: "GLASS CLEANING", charge: 900 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
    "ALTO": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ALTO 800": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ALTO K10": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ALTO K10C": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "A-STAR": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "CELERIO": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "CELERIO CNG": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "IGNIS-PETROL": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "M 800": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "NEW CELERIO 2021": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "NEW WAGON R 1.2L PETROL": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "NEW WAGON R 1L PETROL": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "OMNI": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "RITZ": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "S-PRESSO": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "WAGON R": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "WAGON-R NEW": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ZEN ESTILO": [
    { name: "INTERIOR CLEANING", charge: 1050 },
    { name: "BODY RUBBING & POLISHING", charge: 1050 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 1900 },
    { name: "PAINT PROTECTION", charge: 2900 },
    { name: "SILENCER COATING", charge: 700 },
    { name: "GLASS CLEANING", charge: 800 },
    { name: "AC VENT CLEANING", charge: 650 },
  ]
};
