
export const threeMCareData: { [model: string]: { name: string; charge: number }[] } = {
  "CIAZ DIESEL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "CIAZ PETROL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Ciaz": [ // Alias for CIAZ PETROL and DIESEL
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ERTIGA DIESEL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "ERTIGA PETROL": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
   "Ertiga": [ // Alias
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Fronx": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Baleno": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Grand Vitara": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "S-Cross": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "Brezza": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
  "XL6": [
    { name: "INTERIOR CLEANING", charge: 1500 },
    { name: "BODY RUBBING & POLISHING", charge: 1500 },
    { name: "ANTIRUST/ CHASSIS PAINT", charge: 2500 },
    { name: "PAINT PROTECTION", charge: 4000 },
    { name: "SILENCER COATING", charge: 900 },
    { name: "GLASS CLEANING", charge: 950 },
    { name: "AC VENT CLEANING", charge: 650 },
  ],
};
