
import type { CustomLabor } from './types';

export const customLaborData: CustomLabor[] = [
  // Default Workshop Prices
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Ertiga', charge: 312.7 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Celerio', charge: 274.03 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Wagon R', charge: 278.88 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'S-Presso', charge: 274.03 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Swift', charge: 290.38 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Dzire', charge: 348.45 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Alto 800', charge: 109.61 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Brezza', charge: 236 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Eeco', charge: 103.96 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Alto K10', charge: 274.03 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Baleno', charge: 345 },
  { workshopId: 'default', name: 'BATTERY GROUND CABLE', model: 'Fronx', charge: 300 },
  { workshopId: 'default', name: 'FRONT STRUT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto K10', charge: 876.88 },
  { workshopId: 'default', name: 'FRONT STRUT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ignis', charge: 929.2 },
  { workshopId: 'default', name: 'FRONT STRUT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ertiga', charge: 1000.64 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Alto K10', charge: 438.44 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Swift', charge: 464.6 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Celerio', charge: 438.44 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Wagon R', charge: 383.64 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Dzire', charge: 464.6 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Alto 800', charge: 548.05 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Ciaz', charge: 500.32 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Ertiga', charge: 500.32 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'Baleno', charge: 460 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Wagon R', charge: 493.25 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ertiga', charge: 625.4 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto 800', charge: 164.42 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'S-Cross', charge: 625.4 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto K10', charge: 657.66 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Brezza', charge: 595.9 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Eeco', charge: 259.9 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Dzire', charge: 580.75 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Swift', charge: 580.75 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Baleno', charge: 575 },
  { workshopId: 'default', name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'Celerio', charge: 548.05 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Alto 800', charge: 274.03 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Swift', charge: 696.9 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Dzire', charge: 696.9 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Eeco', charge: 207.92 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Wagon R', charge: 274.03 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Baleno', charge: 805 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'Alto K10', charge: 274.03 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Brezza', charge: 238.36 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ertiga', charge: 250.16 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Swift', charge: 232.3 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'S-Cross', charge: 250.16 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Dzire', charge: 232.3 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ignis', charge: 232.3 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ciaz', charge: 250.16 },
  { workshopId: 'default', name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'Celerio', charge: 219.22 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'Wagon R', charge: 657.66 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'Alto 800', charge: 767.27 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'Dzire', charge: 813.05 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'Swift', charge: 813.05 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'Celerio', charge: 767.27 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'Alto K10', charge: 767.27 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ertiga', charge: 1375.88 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'Wagon R', charge: 986.49 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto K10', charge: 1260.52 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto 800', charge: 1260.52 },
  { workshopId: 'default', name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'Celerio', charge: 1205.71 },
  { workshopId: 'default', name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'Swift', charge: 406.53 },
  { workshopId: 'default', name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'Wagon R', charge: 328.83 },
  { workshopId: 'default', name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'Dzire', charge: 406.53 },
  { workshopId: 'default', name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'Ertiga', charge: 437.78 },
  { workshopId: 'default', name: 'REAR SHOCK ABSORBER (ONE SIDE) WITH OPPOSITE SIDE', model: 'Wagon R', charge: 727.5 },
  { workshopId: 'default', name: 'REAR SHOCK ABSORBER (ONE SIDE) WITH OPPOSITE SIDE', model: 'Dzire', charge: 696.9 },
  { workshopId: 'default', name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'Wagon R', charge: 383.64 },
  { workshopId: 'default', name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'Alto K10', charge: 328.83 },
  { workshopId: 'default', name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'Alto 800', charge: 328.83 },
  { workshopId: 'default', name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'Swift', charge: 987.28 },
  { workshopId: 'default', name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE) WITH OPPOSITE SIDE', model: 'Eeco', charge: 1299.5 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Brezza', charge: 649 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Wagon R', charge: 602.86 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Swift', charge: 638.83 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ertiga', charge: 687.94 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto 800', charge: 602.86 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Baleno', charge: 575 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Alto K10', charge: 602.86 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Dzire', charge: 638.83 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Super Carry', charge: 596.64 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'S-Presso', charge: 602.86 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'XL6', charge: 687.94 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Celerio', charge: 602.86 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Fronx', charge: 500 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Ignis', charge: 638.83 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Grand Vitara', charge: 531 },
  { workshopId: 'default', name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Eeco', charge: 467.82 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Brezza', charge: 354 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Wagon R', charge: 328.83 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Alto 800', charge: 493.25 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Fronx', charge: 250 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Dzire', charge: 348.45 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Swift', charge: 348.45 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Ertiga', charge: 375.24 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'S-Presso', charge: 493.25 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Baleno', charge: 345 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Super Carry', charge: 325.44 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Celerio', charge: 328.83 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Alto K10', charge: 328.83 },
  { workshopId: 'default', name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Eeco', charge: 415.84 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Ertiga', charge: 850 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Baleno', charge: 750 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Swift', charge: 750 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Brezza', charge: 850 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Wagon R', charge: 700 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'S-Presso', charge: 650 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Alto 800', charge: 650 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Fronx', charge: 900 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Celerio', charge: 700 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Eeco', charge: 800 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Grand Vitara', charge: 900 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Ignis', charge: 700 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'XL6', charge: 900 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Dzire', charge: 800 },
  { workshopId: 'default', name: 'STONE GUARD COATING', model: 'Alto K10', charge: 700 },
  { workshopId: 'default', name: 'SILENCER WELDING', model: 'Dzire', charge: 800 },
  { workshopId: 'default', name: 'SILENCER WELDING', model: 'Fronx', charge: 900 },
  { workshopId: 'default', name: 'SILENCER WELDING', model: 'Alto K10', charge: 700 },
  { workshopId: 'default', name: 'SILENCER WELDING', model: 'Wagon R', charge: 700 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Celerio', charge: 274.03 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Dzire', charge: 290.38 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Baleno', charge: 287.5 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Alto 800', charge: 274.03 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Brezza', charge: 295 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Swift', charge: 290.38 },
  { workshopId: 'default', name: 'EVAPORATOR CLEANING', model: 'Ertiga', charge: 312.7 },
];
