import type { CustomLabor } from './types';

export const customLaborData: CustomLabor[] = [
  { name: 'BATTERY GROUND CABLE', model: 'NEW ERTIGA PETROL', charge: 250.16 },
  { name: 'BATTERY GROUND CABLE', model: 'CELERIO', charge: 274.03 },
  { name: 'BATTERY GROUND CABLE', model: 'WAGON-R NEW', charge: 274.03 },
  { name: 'BATTERY GROUND CABLE', model: 'S-PRESSO', charge: 274.03 },
  { name: 'BATTERY GROUND CABLE', model: 'SWIFT NEW/  DZIRE NEW DIESEL', charge: 290.38 },
  { name: 'BATTERY GROUND CABLE', model: 'New Dzire Diesel', charge: 348.45 },
  { name: 'BATTERY GROUND CABLE', model: 'ALTO 800', charge: 109.61 },
  { name: 'BATTERY GROUND CABLE', model: 'OMNI', charge: 155.94 },
  { name: 'BATTERY GROUND CABLE', model: 'NEW CELERIO 2021', charge: 274.03 },
  { name: 'BATTERY GROUND CABLE', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 290.38 },
  { name: 'BATTERY GROUND CABLE', model: 'ALTO', charge: 109.61 },
  { name: 'BATTERY GROUND CABLE', model: 'VITARA BREZZA K15B BS-VI', charge: 236 },
  { name: 'BATTERY GROUND CABLE', model: 'NEW WAGON R 1.2L PETROL', charge: 278.88 },
  { name: 'BATTERY GROUND CABLE', model: 'EECO K12N 2022', charge: 92 },
  { name: 'BATTERY GROUND CABLE', model: 'SWIFT DZIRE', charge: 290.38 },
  { name: 'BATTERY GROUND CABLE', model: 'ALTO K10C', charge: 274.03 },
  { name: 'BATTERY GROUND CABLE', model: 'NEW SWIFT PETROL', charge: 290.38 },
  { name: 'BATTERY GROUND CABLE', model: 'SWIFT DIESEL', charge: 290.38 },
  { name: 'BATTERY GROUND CABLE', model: 'New Dzire Petrol', charge: 348.45 },
  { name: 'BATTERY GROUND CABLE', model: 'MARUTI EECO PETROL', charge: 103.96 },
  { name: 'BATTERY GROUND CABLE', model: 'NEW BALENO', charge: 345 },
  { name: 'BATTERY GROUND CABLE', model: 'MARUTI BALENO PETROL', charge: 287.5 },
  { name: 'BATTERY GROUND CABLE', model: 'NEW BREZZA', charge: 236 },
  { name: 'BATTERY GROUND CABLE', model: 'EECO', charge: 103.96 },
  { name: 'BATTERY GROUND CABLE', model: 'ERTIGA PETROL', charge: 312.7 },
  { name: 'BATTERY GROUND CABLE', model: 'Fronx Domestic P74', charge: 300 },
  { name: 'BATTERY GROUND CABLE', model: 'ALTO K10', charge: 274.03 },
  { name: 'FRONT STRUT (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO K10', charge: 876.88 },
  { name: 'FRONT STRUT (ONE SIDE) WITH OPPOSITE SIDE', model: 'IGNIS-PETROL', charge: 929.2 },
  { name: 'FRONT STRUT (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW ERTIGA PETROL', charge: 1000.64 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'M 800', charge: 555.96 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'ALTO K10', charge: 438.44 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 464.6 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'ZEN ESTILO', charge: 555.96 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'CELERIO', charge: 438.44 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'WAGON-R NEW', charge: 383.64 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'New Dzire Petrol', charge: 464.6 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'ALTO 800', charge: 548.05 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'ALTO', charge: 548.05 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'CIAZ DIESEL', charge: 500.32 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'ERTIGA PETROL', charge: 500.32 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'MARUTI BALENO PETROL', charge: 460 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE)', model: 'WAGON R', charge: 383.64 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'WAGON-R NEW', charge: 493.25 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA PETROL', charge: 625.4 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO 800', charge: 164.42 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'S-CROSS (D13)', charge: 625.4 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO K10', charge: 657.66 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO', charge: 712.47 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'VITARA BREZZA 1.3D', charge: 595.9 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'EECO', charge: 259.9 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'VITARA BREZZA K15B BS-VI', charge: 590 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'SWIFT NEW/  DZIRE NEW DIESEL', charge: 580.75 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 580.75 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA DIESEL', charge: 625.4 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'MARUTI BALENO PETROL', charge: 575 },
  { name: 'FRONT SUSPENSION ARM (ONE SIDE) WITH OPPOSITE SIDE', model: 'CELERIO', charge: 548.05 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'ALTO 800', charge: 274.03 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 696.9 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'SWIFT NEW/  DZIRE NEW DIESEL', charge: 696.9 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'ALTO', charge: 986.49 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'EECO', charge: 207.92 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'WAGON R', charge: 274.03 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'MARUTI BALENO PETROL', charge: 805 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'MARUTI EECO PETROL', charge: 207.92 },
  { name: 'FRONT STABILIZER BAR AND/OR FRONT STABILIZER BAR MOUNT', model: 'ALTO K10', charge: 274.03 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'VITARA BREZZA K15B BS-VI', charge: 236 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA DIESEL', charge: 250.16 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW SWIFT PETROL', charge: 232.3 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'S-CROSS (D13)', charge: 250.16 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW ERTIGA PETROL', charge: 250.16 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'New Dzire Petrol', charge: 232.3 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'IGNIS-PETROL', charge: 232.3 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA PETROL', charge: 250.16 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'CIAZ PETROL', charge: 250.16 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 232.3 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'VITARA BREZZA 1.3D', charge: 238.36 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'DZIRE TOUR DIESEL', charge: 207.92 },
  { name: 'FRONT STABILIZER BAR JOINT (ONE SIDE) WITH OPPOSITE SIDE', model: 'CELERIO', charge: 219.22 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'WAGON-R NEW', charge: 657.66 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'ALTO 800', charge: 767.27 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'New Dzire Petrol', charge: 813.05 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 813.05 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'ALTO', charge: 712.47 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'CELERIO', charge: 767.27 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE)', model: 'ALTO K10', charge: 767.27 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA PETROL', charge: 1375.88 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'WAGON-R NEW', charge: 986.49 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO K10', charge: 1260.52 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'OMNI', charge: 675.74 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO 800', charge: 1260.52 },
  { name: 'FRONT WHEEL BEARING (ONE SIDE) WITH OPPOSITE SIDE', model: 'CELERIO', charge: 1205.71 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 406.53 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'WAGON-R NEW', charge: 328.83 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'SWIFT NEW/  DZIRE NEW DIESEL', charge: 406.53 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE)', model: 'ERTIGA DIESEL', charge: 437.78 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO', charge: 438.44 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW WAGON R 1.2L PETROL', charge: 727.5 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE) WITH OPPOSITE SIDE', model: 'New Dzire Petrol', charge: 696.9 },
  { name: 'REAR SHOCK ABSORBER (ONE SIDE) WITH OPPOSITE SIDE', model: 'WAGON-R NEW', charge: 383.64 },
  { name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'WAGON-R NEW', charge: 383.64 },
  { name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'ALTO K10', charge: 328.83 },
  { name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'ALTO 800', charge: 328.83 },
  { name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'ALTO', charge: 438.44 },
  { name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE)', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 987.28 },
  { name: 'REAR WHEEL BEARING (2WD  DRUM BRAKE  ONE SIDE) WITH OPPOSITE SIDE', model: 'MARUTI EECO PETROL', charge: 1299.5 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'M 800', charge: 602.29 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW BREZZA', charge: 649 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'WAGON-R NEW', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW SWIFT PETROL', charge: 638.83 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW SWIFT DZIRE TOUR S PETROL', charge: 571.78 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW ERTIGA PETROL', charge: 687.94 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO 800', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW BALENO', charge: 575 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'VITARA BREZZA K15B BS-VI', charge: 649 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO K10', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'OMNI', charge: 519.8 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO', charge: 493.25 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 638.83 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'New Dzire Petrol', charge: 638.83 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'SUPER CARRY PETROL', charge: 174.02 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA DIESEL', charge: 687.94 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'S-PRESSO', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'XL6', charge: 687.94 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'VITARA BREZZA 1.3D', charge: 655.49 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW WAGON R 1L PETROL', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW CELERIO 2021', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'CELERIO', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Fronx Turbo Smart Hybrid Domestic P74', charge: 500 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'NEW WAGON R 1.2L PETROL', charge: 613.53 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'Fronx Domestic P74', charge: 500 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'IGNIS-PETROL', charge: 638.83 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'ERTIGA PETROL', charge: 687.94 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'SUPER CARRY PETROL', charge: 596.64 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'EECO K12N 2022', charge: 414 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'MARUTI GRAND VITARA Smart Hybrid', charge: 531 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'MARUTI BALENO PETROL', charge: 632.5 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'ALTO K10C', charge: 602.86 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'MARUTI EECO PETROL', charge: 467.82 },
  { name: 'FRONT BRAKE CALIPER ASSY (ONE SIDE) WITH OPPOSITE SIDE', model: 'DAZZLING NEW DZIRE', charge: 555.5 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'VITARA BREZZA K15B BS-VI', charge: 354 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'WAGON-R NEW', charge: 328.83 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'ALTO 800', charge: 493.25 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'Fronx Turbo Smart Hybrid Domestic P74', charge: 250 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'New Dzire Petrol', charge: 348.45 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW SWIFT PETROL', charge: 348.45 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW ERTIGA PETROL', charge: 375.24 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 348.45 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW WAGON R 1.2L PETROL', charge: 334.65 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'S-PRESSO', charge: 493.25 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW WAGON R 1L PETROL', charge: 328.83 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW BALENO', charge: 287.5 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'SUPER CARRY PETROL', charge: 325.44 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'CELERIO', charge: 328.83 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW CELERIO 2021', charge: 328.83 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'NEW BREZZA', charge: 354 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'ALTO K10C', charge: 328.83 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'ALTO K10', charge: 493.25 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'MARUTI EECO PETROL', charge: 415.84 },
  { name: 'FRONT DISC BRAKE PAD (BOTH SIDES)', model: 'MARUTI BALENO PETROL', charge: 345 },
  { name: 'SWIFT NEW/  DZIRE NEW DIESEL', charge: 348.45 },
  { name: 'STONE GUARD COATING', model: 'NEW ERTIGA PETROL', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'NEW BALENO', charge: 750 },
  { name: 'STONE GUARD COATING', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 750 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1.2L PETROL', charge: 750 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1.2L PETROL', charge: 650 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1.2L PETROL', charge: 650 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1L PETROL', charge: 750 },
  { name: 'STONE GUARD COATING', model: 'S-PRESSO', charge: 650 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'NEW ERTIGA PETROL', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'ALTO 800', charge: 650 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1L PETROL', charge: 650 },
  { name: 'STONE GUARD COATING', model: 'EPIC NEW SWIFT', charge: 750 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 850 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1L PETROL', charge: 650 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 900 },
  { name: 'STONE GUARD COATING', model: 'WAGON-R NEW', charge: 700 },
  { name: 'STONE GUARD COATING', model: 'Fronx Domestic P74', charge: 900 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 900 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1L PETROL', charge: 700 },
  { name: 'STONE GUARD COATING', model: 'CELERIO', charge: 700 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1.2L PETROL', charge: 700 },
  { name: 'STONE GUARD COATING', model: 'EECO K12N 2022', charge: 800 },
  { name: 'STONE GUARD COATING', model: 'MARUTI GRAND VITARA Smart Hybrid', charge: 900 },
  { name: 'STONE GUARD COATING', model: 'IGNIS-PETROL', charge: 700 },
  { name: 'STONE GUARD COATING', model: 'XL6', charge: 900 },
  { name: 'STONE GUARD COATING', model: 'NEW SWIFT PETROL', charge: 800 },
  { name: 'STONE GUARD COATING', model: 'NEW WAGON R 1L PETROL', charge: 703 },
  { name: 'STONE GUARD COATING', model: 'NEW CELERIO 2021', charge: 700 },
  { name: 'STONE GUARD COATING', model: 'DAZZLING NEW DZIRE', charge: 800 },
  { name: 'STONE GUARD COATING', model: 'NEW BREZZA', charge: 950 },
  { name: 'STONE GUARD COATING', model: 'ALTO K10C', charge: 700 },
  { name: 'SILENCER WELDING', model: 'New Dzire Petrol', charge: 800 },
  { name: 'SILENCER WELDING', model: 'Fronx Turbo Smart Hybrid Domestic P74', charge: 900 },
  { name: 'SILENCER WELDING', model: 'Fronx Domestic P74', charge: 900 },
  { name: 'SILENCER WELDING', model: 'ALTO K10C', charge: 700 },
  { name: 'SILENCER WELDING', model: 'NEW WAGON R 1.2L PETROL', charge: 700 },
  { name: 'EVAPORATOR CLEANING', model: 'NEW CELERIO 2021', charge: 274.03 },
  { name: 'EVAPORATOR CLEANING', model: 'New Dzire Petrol', charge: 290.38 },
  { name: 'EVAPORATOR CLEANING', model: 'MARUTI BALENO PETROL', charge: 287.5 },
  { name: 'EVAPORATOR CLEANING', model: 'ALTO 800', charge: 274.03 },
  { name: 'EVAPORATOR CLEANING', model: 'VITARA BREZZA K15B BS-VI', charge: 295 },
  { name: 'EVAPORATOR CLEANING', model: 'NEW SWIFT PETROL', charge: 290.38 },
  { name: 'EVAPORATOR CLEANING', model: 'SWIFT NEW / DZIRE NEW PETROL', charge: 290.38 },
  { name: 'EVAPORATOR CLEANING', model: 'NEW ERTIGA PETROL', charge: 312.7 },
];
