
export const vehicleCategories = {
  "SMALL": [
    "ALTO",
    "ALTO 800",
    "ALTO K10",
    "ALTO K10C",
    "A-STAR",
    "CELERIO",
    "CELERIO CNG",
    "IGNIS-PETROL",
    "M 800",
    "NEW CELERIO 2021",
    "NEW WAGON R 1.2L PETROL",
    "NEW WAGON R 1L PETROL",
    "OMNI",
    "RITZ",
    "S-PRESSO",
    "WAGON R",
    "WAGON-R NEW",
    "ZEN ESTILO"
  ],
  "MEDIUM": [
    "DAZZLING NEW DZIRE",
    "DZIRE TOUR DIESEL",
    "EECO",
    "EECO K12N 2022",
    "EPIC NEW SWIFT",
    "Jimny 5 Door Domestic P74",
    "MARUTI EECO PETROL",
    "New Dzire Diesel",
    "New Dzire Petrol",
    "NEW SWIFT DZIRE TOUR S PETROL",
    "NEW SWIFT PETROL",
    "SWIFT",
    "SWIFT DZIRE",
    "SWIFT NEW / DZIRE NEW PETROL",
    "SWIFT NEW/  DZIRE NEW DIESEL",
    "S-CROSS (D13)",
    "S-CROSS (D16)",
    "VITARA BREZZA 1.3D",
    "VITARA BREZZA K15B BS-VI"
  ],
  "LARGE": [
    "CIAZ DIESEL",
    "CIAZ PETROL",
    "ERTIGA DIESEL",
    "ERTIGA PETROL",
    "Fronx Domestic P74",
    "Fronx Turbo Smart Hybrid Domestic P74",
    "MARUTI BALENO PETROL",
    "MARUTI GRAND VITARA Smart Hybrid",
    "MARUTI GRAND VITARA Strong Hybrid",
    "MARUTI S-CROSS SMART HYBRID 1.5L",
    "NEW BALENO",
    "NEW BREZZA",
    "NEW CIAZ PETROL",
    "NEW ERTIGA PETROL",
    "XL6"
  ]
};
